### ISSUE TITLE
Add links to download release exectables on landing page

### ISSUE THREAD

**Issue by sabaimran** [khoj-ai/landing-page#17]
Desktop applications are mostly tested and working fine.

We want to add links to download the applications directly from within the landing page. Note that:
1. We'll have to build/upload the .dmg arm64 image manually.
2. We'll have to update the links after each release.

**Comment by debanjum** [comment]
- We can link to the latest version of the apps by using:`https://github.com/khoj-ai/khoj/releases/latest/download/<asset_filename>` format. E.g https://github.com/khoj-ai/khoj/releases/latest/download/khoj_amd64.exe etc
  - We should fix up the native app creation workflow to not add the version number to the filename of the generated app. This will keep the artifact name static and allow us to use above static link to always pull the latest released app

- Refer [Github Docs](https://docs.github.com/en/repositories/releasing-projects-on-github/linking-to-releases#linking-to-the-latest-release)

**Comment by akash-singh8** [comment]
@sabaimran is the issue still there?

If so, I feel we can fix this by using the GitHub API to get the latest release version and then add it to the link as mentioned by @debanjum or we can also do it manually i.e. to update the links after each release e.g. for current version [https://github.com/khoj-ai/khoj/releases/download/1.2.1/khoj-1.2.1-x64.exe](https://github.com/khoj-ai/khoj/releases/download/1.2.1/khoj-1.2.1-x64.exe)

**Comment by sabaimran** [comment]
Hi @akash-singh8 ! Yes, we've actually finished this one. You can see the links at https://khoj.dev/downloads. Thanks for reaching out!
