### ISSUE TITLE
Floating footer on Login page

### ISSUE THREAD

**Issue by SDE-ADNAN** [khoj-ai/landing-page#27]
![image](https://github.com/khoj-ai/landing-page/assets/93937216/484ed837-bcf0-4eb7-b2b9-1977ef9c3e14)

**Comment by SDE-ADNAN** [comment]
I want to fix the footer which is currently levitated and make it always  to be bottom 0

**Comment by SDE-ADNAN** [comment]
Maintainers assign it to me

**Comment by sabaimran** [comment]
Hi @SDE-ADNAN ! Thanks for raising this PR. The issue was fixed in this PR: https://github.com/khoj-ai/landing-page/pull/29, so I'll mark this as closed.

**Comment by SDE-ADNAN** [comment]
yeah sure man @sabaimran  thanks for fixing that issue looking forward to contribute more n more !!
