### ISSUE TITLE
Using grids in place of flex boxes in CSS

### ISSUE THREAD

**Issue by sabaimran** [khoj-ai/landing-page#30]
In some parts of the code, flex is being used in place of grids. Use grids for consistency and maintainability.

**Comment by DustyDogCodex** [comment]
hi @sabaimran !

If no one has been assigned to this yet, I would like to work on it. Please assign this issue to me when you get a chance.

Thanks!

**Comment by DustyDogCodex** [comment]
Hi @sabaimran !

Hope you are doing well! Thanks for assigning this issue to me. I will get started on it right away. 

I just had one question before I start. Did you want every instance of flex being changed to grid or just specific sections where grid would be more appropriate? If you could clarify that for me I would appreciate it :)

Thanks!

**Comment by sabaimran** [comment]
Closed with #31 .
